import Head from "next/head";
import contactUs from '@/styles/contact.module.scss';
import { useEffect, useRef } from "react";
import image from '../assets/contact.png'
import Image from "next/image";
import { useRouter } from "next/router";


const contact = ()=>{

    return(
        <>
        <Head>
          <title>Tours</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico"/>
          
          
        </Head>
        <main className="container pt-lg-0 pt-3 ">
          <div className="row  pt-lg-0 pt-0  ">

            <Image 
              src={image}
              alt='background'
              quality={100}
              fill
              className={contactUs.image}
              style={{objectFit:"cover"}}

            />

            <section className="col-lg-6 mx-auto mb-lg-3 mb-5 mb-md-3 ">
                <h1 id={contactUs.cap}>Iben Hildelof</h1>
                <p className="" id={contactUs.moreTxt}>
                    to popular belief, Lorem Ipsum is not simply random text. <br/>
                    It has roots in a piece of classical Latin literature from 45 BC, <br/>
                    making it over 2000 years old. Richard McClintock, a Latin professor
                    at Hampden-Sydney College in Virginia.
                </p>
            </section>

            <div className="row ">
            <section className="col-lg-6 mx-auto mb-lg-3 mb-5 mb-md-3">
                <h1 id={contactUs.cap}>Danny Marthen</h1>
                <p className="" id={contactUs.moreTxt}>
                    to popular belief, Lorem Ipsum is not simply random text. <br/>
                    It has roots in a piece of classical Latin literature from 45 BC, <br/>
                    making it over 2000 years old. Richard McClintock, a Latin professor
                    at Hampden-Sydney College in Virginia.
                </p>
            </section>
            </div>

            <div className="row">
            <section className="col-lg-6 mx-auto">
                <h1 id={contactUs.cap}>Owen Spectrac</h1>
                <p className="" id={contactUs.moreTxt}>
                    to popular belief, Lorem Ipsum is not simply random text. <br/>
                    It has roots in a piece of classical Latin literature from 45 BC, <br/>
                    making it over 2000 years old. Richard McClintock, a Latin professor 
                    at Hampden-Sydney College in Virginia.
                </p>
            </section>
            </div>

           
          </div>
        </main>
      </>


)}
export default contact;