import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';
import feedMenu from '../styles/front.module.scss'







const MyFeed = ()=>{

    
    

    return(

        <>
        
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container pt-lg-5 pt-md-0' id={feedMenu.feed}>

       <div className='row mt-lg-5 pt-lg-5'>

       <h1 className='col-12 mb-3'  id={feedMenu.cap}>light in a <span id={feedMenu.box}>box</span></h1>

        <div className='row' id={feedMenu.moreTxt}>

        <p className='col-12'>Contrary to popular belief, Lorem Ipsum is not simply random text. <br/> It has roots in a piece of classical Lation Literature from 45 BC. <br/>making it over 2000 years old. Richard McClintock, a Latin professor <br/>at Hampden-Sydney College in Virginia,</p>

        <div className='row'>

        <p className='col-12'>looked up one of the more obscure Lation words, consectetur <br/>from a Lorem Ipsum passage, and going through the cites of the word <br/>in classical literature, discovered the undoubtable source. <br/>Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de</p>
        </div>
        </div>
       </div>

      </div>
      




        </>
    );
}
export default MyFeed;