import { useState } from 'react';
import { Modal, Button, Form } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import navMenu from '@/styles/nav.module.scss';
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/router';
import Head from 'next/head';
import logo from '../assets/logo-final.png';

const MyNav = () => {
  const alias = ["about", "tours", "contact"];
  const router = useRouter();

 
  const [showModal, setShowModal] = useState(false);
  const [validated, setValidated] = useState(false);

  

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    const form = event.currentTarget;
    if (form.checkValidity() === false) {
      event.preventDefault();
      event.stopPropagation();
    }
    setValidated(true);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container p-0">
        <nav id={navMenu.nav_desktop} className="row mt-5 ms-auto mb-5 me-0">
          <Link href="/" className="col-lg-3 col-md-4 me-lg-4 col-sm-5 col-12 ps-0 pe-0 ps-4 ps-md-0 ps-lg-0">
            <Image src={logo} alt="logo" className="img-fluid " />
          </Link>

          <ul
            id={navMenu.outline}
            className="col-lg-4 col-md-5 col-sm-6 col-10 mx-auto mt-4 text-center p-2 pe-0 "
          >
            {alias.map((ar, index) => (
              <li className={`ms-2 me-2 ${router.pathname === `/${ar}` ? navMenu.active : ''}`} key={index}>
                <Link href={ar === "about" ? "/" : `/${ar}`}>
                  <span>{ar.toUpperCase()}</span>
                </Link>
              </li>
            ))}
          </ul>

          <button
            type="button"
            className="btn col-1 d-none d-lg-block d-md-block mt-4 text-center p-1 mb-3 ms-auto me-0"
            id={navMenu.time}
            onClick={() => {
              if (router.pathname === "/tours", "about", "contact") {
                setShowModal(true);
              }
            }}
          >
            Book a time
          </button>
        </nav>
      </div>


      <Modal show={showModal} onHide={() => setShowModal(false)} >
  <Modal.Header closeButton>
    <Modal.Title className='mx-auto' id={navMenu.modal}>Fill in and submit the form and we will contact you</Modal.Title>
  </Modal.Header>
  <Modal.Body>
    <Form noValidate validated={validated} onSubmit={handleSubmit}>
      <Form.Group className="mb-3 w-100" controlId="name">
        <Form.Label>Name</Form.Label>
        <Form.Control required type="text" placeholder="" />
        <Form.Control.Feedback type="invalid">
          Please enter your name.
        </Form.Control.Feedback>
      </Form.Group>

      <Form.Group className="mb-3" controlId="email">
        <Form.Label>Email</Form.Label>
        <Form.Control required type="email" placeholder="" />
        <Form.Control.Feedback type="invalid">
          Please enter a valid email address.
        </Form.Control.Feedback>
      </Form.Group>

      <Form.Group className="mb-3" controlId="comment">
        <Form.Label>Comment</Form.Label>
        <Form.Control as="textarea" rows={4} required placeholder="" />
        <Form.Control.Feedback type="invalid">
          Please enter your comment.
        </Form.Control.Feedback>
      </Form.Group>

      <div className='row'>
        <Button className='col-2 ms-auto me-lg-3' id={navMenu.submit} type="submit">Submit</Button>
      </div>
    </Form>
  </Modal.Body>
</Modal>

    </>
  );
};

export default MyNav;